parameters:
  branch: 'gh-pages'

stages:
- stage: 
  displayName: 'Publish blog contents to GitHub Pages'
  jobs:
  - deployment: 
    variables:
    - group: jpazinteg-blog-publish-to-prod
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'jpazinteg-blog-prod'
    strategy:
      runOnce:
        deploy:
          steps: 
          - task: InstallSSHKey@0
            inputs:
              knownHostsEntry: $(GITHUB_HOST_PUBLIC_KEY)
              sshKeySecureFile: 'jpazinteg-github-deploy-private-key'
            displayName: 'Install SSH Deploy Key'

          - script: |
              set -euo pipefail
              cd $(Build.ArtifactStagingDirectory)
              GITHUB_REPO="git@github.com:Yiwen-Chen/blog.git"

              # Clone gh-pages if exists, otherwise create orphan branch
              if git ls-remote --exit-code "$GITHUB_REPO" refs/heads/${{ parameters.branch }} > /dev/null 2>&1; then
                git clone -b ${{ parameters.branch }} "$GITHUB_REPO" blog
                rm -rf blog/*
              else
                mkdir blog && cd blog
                git init
                git checkout --orphan ${{ parameters.branch }}
                git remote add origin "$GITHUB_REPO"
                cd ..
              fi
              ls -a $(Build.ArtifactStagingDirectory)/blog
            displayName: 'Git clone or init gh-pages branch'

          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/drop/jpazinteg-blog.zip'
              cleanDestinationFolder: false
              destinationFolder: '$(Agent.TempDirectory)/blog'

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Agent.TempDirectory)/blog'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/blog'
              OverWrite: true

          - script: |
              cd $(Build.ArtifactStagingDirectory)/blog
              touch .nojekyll
              git config user.name "Azure Pipelines"
              git config user.email "azuredevops@users.noreply.github.com"
              git add .
              git commit -m "Publish from pipeline, commit: $(Build.SourceVersion)"
              git log -1 --stat
              git push origin ${{ parameters.branch }}
            displayName: 'Push HTML to gh-pages on GitHub'
