trigger:
  branches:
    include:
    - 'main'
  paths:
    exclude:
    - 'README.md'
    - '.gitignore'

stages:
- template: stages/push-source-to-github.yml
- template: stages/generate-blog.yml
- template: stages/publish-to-ghpages.yml
